### ISSUE TITLE
iOS: Tutorials Page

### ISSUE THREAD

**Issue by wrenliang** [ubclaunchpad/dough-bros#22]

**Comment by ttagore23** [comment]
What are we supposed to do for the tutorials page?

**Comment by wrenliang** [comment]
Basically, when a user first downloads the app we want to show them a slideshow of screenshots and text describing the core features of our app and where to find them. So for the Tutorials Page, we need to build out the views and controllers that support that functionality (slideshow of screens with forward, back, and skip buttons)
